# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Tue Aug 22 16:54:39 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.Qwt5 import QwtPlot

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(914, 624)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_current_state = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_state.setFont(font)
        self.label_current_state.setFrameShape(QtGui.QFrame.Box)
        self.label_current_state.setObjectName(_fromUtf8("label_current_state"))
        self.gridLayout_2.addWidget(self.label_current_state, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_sensor = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor.setFont(font)
        self.label_sensor.setObjectName(_fromUtf8("label_sensor"))
        self.horizontalLayout.addWidget(self.label_sensor)
        self.label_humidity = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_humidity.setFont(font)
        self.label_humidity.setObjectName(_fromUtf8("label_humidity"))
        self.horizontalLayout.addWidget(self.label_humidity)
        self.doubleSpinBox_humidity = QtGui.QDoubleSpinBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_humidity.setFont(font)
        self.doubleSpinBox_humidity.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_humidity.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.doubleSpinBox_humidity.setAutoFillBackground(True)
        self.doubleSpinBox_humidity.setWrapping(False)
        self.doubleSpinBox_humidity.setFrame(True)
        self.doubleSpinBox_humidity.setReadOnly(False)
        self.doubleSpinBox_humidity.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_humidity.setSpecialValueText(_fromUtf8(""))
        self.doubleSpinBox_humidity.setPrefix(_fromUtf8(""))
        self.doubleSpinBox_humidity.setDecimals(2)
        self.doubleSpinBox_humidity.setMaximum(109.99)
        self.doubleSpinBox_humidity.setObjectName(_fromUtf8("doubleSpinBox_humidity"))
        self.horizontalLayout.addWidget(self.doubleSpinBox_humidity)
        self.label_temperature = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_temperature.setFont(font)
        self.label_temperature.setObjectName(_fromUtf8("label_temperature"))
        self.horizontalLayout.addWidget(self.label_temperature)
        self.doubleSpinBox_temperature = QtGui.QDoubleSpinBox(self.frame_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_temperature.setFont(font)
        self.doubleSpinBox_temperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_temperature.setAutoFillBackground(True)
        self.doubleSpinBox_temperature.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_temperature.setMaximum(109.99)
        self.doubleSpinBox_temperature.setObjectName(_fromUtf8("doubleSpinBox_temperature"))
        self.horizontalLayout.addWidget(self.doubleSpinBox_temperature)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_sensor_1 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor_1.setFont(font)
        self.label_sensor_1.setObjectName(_fromUtf8("label_sensor_1"))
        self.horizontalLayout_5.addWidget(self.label_sensor_1)
        self.label_humidity_1 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_humidity_1.setFont(font)
        self.label_humidity_1.setObjectName(_fromUtf8("label_humidity_1"))
        self.horizontalLayout_5.addWidget(self.label_humidity_1)
        self.doubleSpinBox_humidity1 = QtGui.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_humidity1.setFont(font)
        self.doubleSpinBox_humidity1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_humidity1.setAutoFillBackground(True)
        self.doubleSpinBox_humidity1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_humidity1.setSpecialValueText(_fromUtf8(""))
        self.doubleSpinBox_humidity1.setMaximum(109.99)
        self.doubleSpinBox_humidity1.setObjectName(_fromUtf8("doubleSpinBox_humidity1"))
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_humidity1)
        self.label_temperature_1 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_temperature_1.setFont(font)
        self.label_temperature_1.setObjectName(_fromUtf8("label_temperature_1"))
        self.horizontalLayout_5.addWidget(self.label_temperature_1)
        self.doubleSpinBox_temperature1 = QtGui.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_temperature1.setFont(font)
        self.doubleSpinBox_temperature1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_temperature1.setAutoFillBackground(True)
        self.doubleSpinBox_temperature1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_temperature1.setMaximum(109.99)
        self.doubleSpinBox_temperature1.setObjectName(_fromUtf8("doubleSpinBox_temperature1"))
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_temperature1)
        self.gridLayout_2.addWidget(self.frame, 2, 0, 1, 1)
        self.frame1 = QtGui.QFrame(self.centralwidget)
        self.frame1.setFrameShape(QtGui.QFrame.Box)
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_sensor_2 = QtGui.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor_2.setFont(font)
        self.label_sensor_2.setObjectName(_fromUtf8("label_sensor_2"))
        self.horizontalLayout_2.addWidget(self.label_sensor_2)
        self.label_humidity_2 = QtGui.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_humidity_2.setFont(font)
        self.label_humidity_2.setObjectName(_fromUtf8("label_humidity_2"))
        self.horizontalLayout_2.addWidget(self.label_humidity_2)
        self.doubleSpinBox_humidity2 = QtGui.QDoubleSpinBox(self.frame1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_humidity2.setFont(font)
        self.doubleSpinBox_humidity2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_humidity2.setAutoFillBackground(True)
        self.doubleSpinBox_humidity2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_humidity2.setMaximum(109.99)
        self.doubleSpinBox_humidity2.setObjectName(_fromUtf8("doubleSpinBox_humidity2"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_humidity2)
        self.label_temperature_2 = QtGui.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_temperature_2.setFont(font)
        self.label_temperature_2.setObjectName(_fromUtf8("label_temperature_2"))
        self.horizontalLayout_2.addWidget(self.label_temperature_2)
        self.doubleSpinBox_temperature2 = QtGui.QDoubleSpinBox(self.frame1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_temperature2.setFont(font)
        self.doubleSpinBox_temperature2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_temperature2.setAutoFillBackground(True)
        self.doubleSpinBox_temperature2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_temperature2.setMaximum(109.99)
        self.doubleSpinBox_temperature2.setObjectName(_fromUtf8("doubleSpinBox_temperature2"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_temperature2)
        self.gridLayout_2.addWidget(self.frame1, 0, 1, 1, 1)
        self.frame2 = QtGui.QFrame(self.centralwidget)
        self.frame2.setFrameShape(QtGui.QFrame.Box)
        self.frame2.setObjectName(_fromUtf8("frame2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_sensor_3 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor_3.setFont(font)
        self.label_sensor_3.setObjectName(_fromUtf8("label_sensor_3"))
        self.horizontalLayout_3.addWidget(self.label_sensor_3)
        self.label_humidity_3 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_humidity_3.setFont(font)
        self.label_humidity_3.setObjectName(_fromUtf8("label_humidity_3"))
        self.horizontalLayout_3.addWidget(self.label_humidity_3)
        self.doubleSpinBox_humidity3 = QtGui.QDoubleSpinBox(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_humidity3.setFont(font)
        self.doubleSpinBox_humidity3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_humidity3.setAutoFillBackground(True)
        self.doubleSpinBox_humidity3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_humidity3.setMaximum(109.99)
        self.doubleSpinBox_humidity3.setObjectName(_fromUtf8("doubleSpinBox_humidity3"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_humidity3)
        self.label_temperature_3 = QtGui.QLabel(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_temperature_3.setFont(font)
        self.label_temperature_3.setObjectName(_fromUtf8("label_temperature_3"))
        self.horizontalLayout_3.addWidget(self.label_temperature_3)
        self.doubleSpinBox_temperature3 = QtGui.QDoubleSpinBox(self.frame2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_temperature3.setFont(font)
        self.doubleSpinBox_temperature3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_temperature3.setAutoFillBackground(True)
        self.doubleSpinBox_temperature3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_temperature3.setMaximum(109.99)
        self.doubleSpinBox_temperature3.setObjectName(_fromUtf8("doubleSpinBox_temperature3"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_temperature3)
        self.gridLayout_2.addWidget(self.frame2, 1, 1, 1, 1)
        self.frame3 = QtGui.QFrame(self.centralwidget)
        self.frame3.setFrameShape(QtGui.QFrame.Box)
        self.frame3.setObjectName(_fromUtf8("frame3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_sensor_4 = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_sensor_4.setFont(font)
        self.label_sensor_4.setObjectName(_fromUtf8("label_sensor_4"))
        self.horizontalLayout_4.addWidget(self.label_sensor_4)
        self.label_humidity_4 = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_humidity_4.setFont(font)
        self.label_humidity_4.setObjectName(_fromUtf8("label_humidity_4"))
        self.horizontalLayout_4.addWidget(self.label_humidity_4)
        self.doubleSpinBox_humidity4 = QtGui.QDoubleSpinBox(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_humidity4.setFont(font)
        self.doubleSpinBox_humidity4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_humidity4.setAutoFillBackground(True)
        self.doubleSpinBox_humidity4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_humidity4.setMaximum(109.99)
        self.doubleSpinBox_humidity4.setObjectName(_fromUtf8("doubleSpinBox_humidity4"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_humidity4)
        self.label_temperature_4 = QtGui.QLabel(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_temperature_4.setFont(font)
        self.label_temperature_4.setObjectName(_fromUtf8("label_temperature_4"))
        self.horizontalLayout_4.addWidget(self.label_temperature_4)
        self.doubleSpinBox_temperature4 = QtGui.QDoubleSpinBox(self.frame3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_temperature4.setFont(font)
        self.doubleSpinBox_temperature4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_temperature4.setAutoFillBackground(True)
        self.doubleSpinBox_temperature4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_temperature4.setMaximum(109.99)
        self.doubleSpinBox_temperature4.setObjectName(_fromUtf8("doubleSpinBox_temperature4"))
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_temperature4)
        self.gridLayout_2.addWidget(self.frame3, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.qwtPlot = QwtPlot(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        self.qwtPlot.setFont(font)
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.verticalLayout.addWidget(self.qwtPlot)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Humidity control with SHT75", None))
        self.label_current_state.setText(_translate("MainWindow", "Current state: OFF", None))
        self.label_sensor.setText(_translate("MainWindow", "1", None))
        self.label_humidity.setText(_translate("MainWindow", "Humidity", None))
        self.doubleSpinBox_humidity.setSuffix(_translate("MainWindow", "%", None))
        self.label_temperature.setText(_translate("MainWindow", "<html><head/><body><p>Temperature</p></body></html>", None))
        self.doubleSpinBox_temperature.setSuffix(_translate("MainWindow", " °C", None))
        self.label_sensor_1.setText(_translate("MainWindow", "2", None))
        self.label_humidity_1.setText(_translate("MainWindow", "Humidity", None))
        self.doubleSpinBox_humidity1.setSuffix(_translate("MainWindow", "%", None))
        self.label_temperature_1.setText(_translate("MainWindow", "<html><head/><body><p>Temperature</p></body></html>", None))
        self.doubleSpinBox_temperature1.setSuffix(_translate("MainWindow", " °C", None))
        self.label_sensor_2.setText(_translate("MainWindow", "3", None))
        self.label_humidity_2.setText(_translate("MainWindow", "Humidity", None))
        self.doubleSpinBox_humidity2.setSuffix(_translate("MainWindow", "%", None))
        self.label_temperature_2.setText(_translate("MainWindow", "<html><head/><body><p>Temperature</p></body></html>", None))
        self.doubleSpinBox_temperature2.setSuffix(_translate("MainWindow", " °C", None))
        self.label_sensor_3.setText(_translate("MainWindow", "4", None))
        self.label_humidity_3.setText(_translate("MainWindow", "Humidity", None))
        self.doubleSpinBox_humidity3.setSuffix(_translate("MainWindow", "%", None))
        self.label_temperature_3.setText(_translate("MainWindow", "<html><head/><body><p>Temperature</p></body></html>", None))
        self.doubleSpinBox_temperature3.setSuffix(_translate("MainWindow", " °C", None))
        self.label_sensor_4.setText(_translate("MainWindow", "5", None))
        self.label_humidity_4.setText(_translate("MainWindow", "Humidity", None))
        self.doubleSpinBox_humidity4.setSuffix(_translate("MainWindow", "%", None))
        self.label_temperature_4.setText(_translate("MainWindow", "<html><head/><body><p>Temperature</p></body></html>", None))
        self.doubleSpinBox_temperature4.setSuffix(_translate("MainWindow", " °C", None))


